# Questions 1 :
### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2 :
### Accept two lists of 5 elements each from the user.
### Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy as np

lst = []
lst2 = []

for i in range(5):
    lst1 = (int(input())) 
    lst.append(lst1)
    
print()    

for i in range(5):
    lst3 = (int(input())) 
    lst2.append(lst3)
    
print()   

arr1 = np.array(lst)
arr2 = np.array(lst2)
arr3 = np.concatenate((arr1,arr2))
print(arr3)
arr4 = np.sort(arr3)
print(arr4);

1
4
7
8
5

2
3
6
9
0

[1 4 7 8 5 2 3 6 9 0]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# import numpy as np

# arr1,arr2 = (list(map(int,input().split())) for i in range(2))

# arr1 = np.array(arr1)
# arr2 = np.array(arr2)

# print(np.concatenate((arr1,arr2)))

# print(np.sort(np.concatenate((arr1,arr2))))

# Questions 3 :
### Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
import numpy as np

arr = np.array([[12,24,36,15,30,45],[16,32,64,17,34,51]])
print(arr.shape)
print(arr.size)

(2, 6)
12


# Questions 4 :
### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
### Hint: np.newaxis, np.expand_dims

In [12]:
import numpy as np

arr = np.array([[41, 42, 43, 44, 45,46]])
print(arr, arr.shape)

# arr_2 = np.expand_dims(arr,axis = 1)
# print(arr_2)

print()
arr2 = arr.reshape(3,2)
print(arr2, arr2.shape)

[[41 42 43 44 45 46]] (1, 6)

[[41 42]
 [43 44]
 [45 46]] (3, 2)


# Questions 5 :
### Consider two square numpy arrays. Stack them vertically and horizontally.
### Hint: Use vstack(), hstack()

In [6]:
import numpy as np
x = np.array([[3], [5], [7]])
y = np.array([[5], [7], [9]])
np.vstack((x,y))

array([[3],
       [5],
       [7],
       [5],
       [7],
       [9]])

In [7]:
import numpy as np
x = np.array([[3], [5], [7]])
y = np.array([[5], [7], [9]])
np.hstack((x,y))

array([[3, 5],
       [5, 7],
       [7, 9]])

# Questions 6 :
### How to get unique items and counts of unique items?

In [8]:
import numpy as np
number_list = np.array([1, 1, 2, 3, 4, 4, 1, 5, 6, 3, 4, 2, 5])

(unique, counts) = np.unique(number_list, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 3]
 [2 2]
 [3 2]
 [4 3]
 [5 2]
 [6 1]]


In [1]:
# list1 = [1,3,1,5,2,4,7,6,2]

# list1 = list(set(list1))

# print(list1)